filebeat.inputs:

- type: log

  # Change to true to enable this input configuration.
  enabled: true

  # Paths that should be crawled and fetched. Glob based paths.
  paths:
   - /usr/share/filebeat/logs/dpkg.log ## directory log
filebeat.config.modules:
  # Glob pattern for configuration loading
  path: /usr/share/filebeat/modules.d/*.yml

  # Set to true to enable config reloading
  reload.enabled: false
output.logstash:
  # The Logstash hosts
  hosts: ["localhost:5044"]
setup.kibana:
  host: "localhost:5601"
